apiVersion: sql.gcp.upbound.io/v1beta2
kind: DatabaseInstance
metadata:
  name: app-postgres
spec:
  forProvider:
    region: australia-southeast1
    project: my-gcp-project
    databaseVersion: POSTGRES_16
    deletionProtection: true
    settings:
      - tier: db-custom-4-16384
        availabilityType: REGIONAL
        diskSize: 50
        diskType: PD_SSD
        backupConfiguration:
          - enabled: true
            pointInTimeRecoveryEnabled: true
        ipConfiguration:
          - ipv4Enabled: false
            privateNetworkRef:
              name: prod-network
  providerConfigRef:
    name: gcp-prod
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: Database
metadata:
  name: app-database
spec:
  forProvider:
    instanceRef:
      name: app-postgres
    project: my-gcp-project
    charset: UTF8
    collation: en_US.UTF8
  providerConfigRef:
    name: gcp-prod
